### ISSUE TITLE
cannot find module typescript-mix/dist

### ISSUE THREAD

**Issue by rizkyramadhan** [michaelolof/typescript-mix#2]
![image](https://user-images.githubusercontent.com/126301/38235764-6fdd0fc2-374c-11e8-8f13-6e8bdd3d0ac3.png)

**Comment by jubairsaidi** [comment]
same thing: on build too.
![](https://d2ffutrenqvap3.cloudfront.net/items/1q422p3H0U2r341m2y02/Screen%20Shot%202018-04-03%20at%201.36.02%20PM.png?v=30b54844)

**Comment by michaelolof** [comment]
Sorry for the delay.
Seems there's been an update on how the typescript engine reads declaration files.
Anyways it has been fixed in the latest update

Thanks for using.
